/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mstore.app;

import mstore.list.LinkedList;

import static mstore.utilities.StringUtils.join;
import static mstore.utilities.StringUtils.split;
import static mstore.app.MessageUtils.getMessage;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        System.out.println(join(tokens));
    }
}
